name: Unit Tests

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  publish-package:
    name: Publish NuGet Package
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up .Net 8.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.X

      - name: Pack
        run: dotnet pack -c Release

      - name: Publish
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: find . -maxdepth 4 -type f -name '*.nupkg' -exec bash -c "dotnet nuget push '{}' --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json --skip-duplicate" \;