name: Unit Tests

on:
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Set up .Net 8.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.X
      
      - name: Run Unit Tests
        run: find *.Tests -maxdepth 0 -type d \( ! -name . \) -exec bash -c "cd '{}' && dotnet test --collect:\"XPlat Code Coverage\" --settings coverlet.runsettings" \;
        
      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: "*.Tests/**/TestResults/**/coverage.cobertura.xml"
          badge: false
          fail_below_min: true
          format: text
          hide_branch_rate: true
          hide_complexity: true
          indicators: false
          thresholds: '80 90'